"""Block assistant attribution markers from re-entering tracked source.

No tracked text may carry assistant/tool co-author trailers or generated-by
marketing lines.

Vendor product names and model ids are not attribution and are explicitly
whitelisted.

History is out of scope: branch protection blocks force-push, so old
commit trailers stay. This test guards the working tree, not the reflog.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent

_ASSISTANT = "Cl" + "aude"

_BANNED = (
    f"Co-Authored-By: {_ASSISTANT}",
    f"co-authored-by: {_ASSISTANT.lower()}",
    f"built with {_ASSISTANT}",
    f"written by {_ASSISTANT}",
    f"generated by {_ASSISTANT}",
)

# Names that are NOT attribution. Used to guard against banning vendor
# products and model identifiers.
_PRODUCT_NAMES = (
    "Claude Code",
    "claude-code",
    "claude-opus-4.7",
    "claude-sonnet-4.6",
    "claude-haiku-4.5",
)


def _tracked_files() -> list[Path]:
    out = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    paths: list[Path] = []
    for line in out.splitlines():
        path = ROOT / line
        if not path.is_file():
            continue
        paths.append(path)
    return paths


def test_no_assistant_attribution_in_tracked_files():
    """No tracked source file carries the banned attribution markers."""
    offenders: list[tuple[str, str]] = []
    for path in _tracked_files():
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        lowered = text.lower()
        for marker in _BANNED:
            if marker.lower() in lowered:
                offenders.append((str(path.relative_to(ROOT)), marker))
    assert not offenders, "Banned attribution markers found in tracked files:\n  " + "\n  ".join(
        f"{path} contains {marker!r}" for path, marker in offenders
    )


def test_vendor_product_names_are_whitelisted():
    """Vendor product names and model ids must keep passing the lint."""
    for name in _PRODUCT_NAMES:
        assert "Co-Authored-By" not in name
        assert "built with" not in name
        assert "generated by" not in name
