"""Block the Claude attribution trailer from re-entering tracked source.

Per CLAUDE.md's `## Commit attribution policy`, no tracked text may
carry these markers:

  - `Co-Authored-By: Claude`
  - `built with Claude`
  - `written by Claude`
  - `generated by Claude`

The vendor product name `Claude Code` and model id `claude-opus-4.7`
are not attribution and are explicitly whitelisted.

History is out of scope: branch protection blocks force-push, so old
commit trailers stay. This test guards the working tree, not the
reflog.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent

_BANNED = (
    "Co-Authored-By: Claude",
    "co-authored-by: claude",
    "built with Claude",
    "written by Claude",
    "generated by Claude",
)

# Names that are NOT attribution. Used to whitelist substrings inside
# longer banned-shaped phrases (none today; reserved).
_PRODUCT_NAMES = (
    "Claude Code",
    "claude-code",
    "claude-opus-4.7",
    "claude-sonnet-4.6",
    "claude-haiku-4.5",
)


def _tracked_files() -> list[Path]:
    out = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    paths: list[Path] = []
    for line in out.splitlines():
        path = ROOT / line
        if not path.is_file():
            continue
        # Skip the policy file and its own test (would self-trip).
        if line == "CLAUDE.md":
            continue
        if line == "CONTRIBUTING.md":
            continue
        if line.startswith("tests/test_attribution_policy"):
            continue
        # Skip planning artefacts that quote the banned strings as
        # documentation of the rule.
        if line.startswith("docs/release-and-ux-overhaul/"):
            continue
        if line.startswith("docs/persona-overhaul/"):
            continue
        # Skip historical changelog entries we cannot rewrite without
        # force-push to a protected branch.
        if line == "CHANGELOG.md":
            continue
        paths.append(path)
    return paths


def test_no_claude_attribution_in_tracked_files():
    """No tracked source file carries the banned attribution markers."""
    offenders: list[tuple[str, str]] = []
    for path in _tracked_files():
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        lowered = text.lower()
        for marker in _BANNED:
            if marker.lower() in lowered:
                offenders.append((str(path.relative_to(ROOT)), marker))
    assert not offenders, "Banned attribution markers found in tracked files:\n  " + "\n  ".join(
        f"{path} contains {marker!r}" for path, marker in offenders
    )


def test_vendor_product_names_are_whitelisted():
    """`Claude Code` and model ids must keep passing the lint."""
    # All product names contain the word Claude but are NOT attribution.
    # This test guards against an over-aggressive future tightening that
    # accidentally bans the vendor product itself.
    for name in _PRODUCT_NAMES:
        assert "Co-Authored-By" not in name
        assert "built with" not in name
        assert "generated by" not in name
